project:
  title: "Santiago Sotelo | CientÃ­fico social de datos"
  type: website
  output-dir: ./_site/es

website:
  title: "Santiago Sotelo"
  navbar:
    right:
      - href: about.qmd
        text: Sobre mÃ­
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
      - href: ../en
        text: ğŸŒ English

lang: es

format:
  html:
    theme: cosmo
    css: styles.css





