project:
  title: "Santiago Sotelo | Social Data Scientist"
  type: website
  output-dir: ./_site/en

website:
  title: "Santiago Sotelo"
  navbar:
    right:
      - href: about.qmd
        text: About me
      - icon: github
        href: https://github.com/aito123/
      - icon: twitter
        href: https://twitter.com/Santiag87589621/
      - icon: linkedin
        href: https://www.linkedin.com/in/santiago-sotelo-989574171/
      - href: ../es
        text: ğŸŒ EspaÃ±ol

lang: en

format:
  html:
    theme: cosmo
    css: styles.css




